### PR TITLE
fix timing units

### PR DESCRIPTION
**Pull request by mikowals**
fix timing to be 'ms' as labeled (`now()` returns time in nanoseconds).  Also multiplied the percentages by 100 so the range from 0 to 100 rather than 0 to 1.

I dried out the code some to make my changes easier to implement.  The operation labels should probably just contain the name without colon and spacing so that they can be reused in more places.  Then the printing could be aligned with a reusable  `pad_to` function to pad any string to required length with spaces.  

`unroll` is only used because all the obvious ways to get the 'StringLiteral` out of a list appear to require the index as a parameter which  a simple for loop can not do.

### CODE REVIEW

**Comment by TilliFe** [comment]
Great Job! Thank you. I appreciate it. :)

**Comment by TilliFe** [comment]
Do you now, how to round to a certain number of digits after the comma in Mojo?

**Comment by mikowals** [comment]
I think `math.trunc` or `math.round` would do what you want, though I haven't tried using them for print formatting.

**Comment by mikowals** [comment]
FYI, I just saw some modular code doing print formatting like this:

```
let py = Python.import_module("builtins")
_ = py.print(
    py.str("{:<15} {:>8.3f} GFLOPS {:>15.2f}x faster than Python").format(
        str, gflops, speedup
    )
)
```

Might be the easiest option.

**Pull request merged**
